version: '3.10'
services:
  front:
    volumes:
      - ./front/:/front/
      - ./data:/data
    env_file:
      - front/.env
    build:
      context: ./front
      dockerfile: Dockerfile
    container_name: front
    ports:
      - "8501:8501"
    restart: always
    depends_on:
      - back
    networks:
      - app_chain

  back:
    build:
      context: ./back
      dockerfile: Dockerfile
    env_file:
      - back/.env
    volumes:
      - ./back/:/back/
      - ./data:/data
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - "8000:8000"
    networks:
      - app_chain


networks:
  app_chain:
    driver: bridge